# -*- coding: utf-8 -*-
"""CapstoneWeek1Peer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXpe99wJXLo4LS8VAXM7oJkGwv9muPIv
"""

import pandas as pd
import numpy as np

print('Hello Capstone Project Course!')

